### ISSUE TITLE
大神，有Mysql的MySqlDbHelper.ttinclude文件吗？

### ISSUE THREAD

**Issue by atorzhang** [chi8708/NBCZ_Admin_NetCore#1]
大神，这只能生成MSSQL的数据实体，有Mysql的MySqlDbHelper.ttinclude文件吗？

**Comment by chi8708** [comment]
暂时不有




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "atorzhang"<notifications@github.com&gt;; 
发送时间: 2020年11月30日(星期一) 下午4:29
收件人: "chi8708/NBCZ_Admin_NetCore"<NBCZ_Admin_NetCore@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [chi8708/NBCZ_Admin_NetCore] 大神，有Mysql的MySqlDbHelper.ttinclude文件吗？ (#1)





 
大神，这只能生成MSSQL的数据实体，有Mysql的MySqlDbHelper.ttinclude文件吗？
